#lang sicp

(define (make-account password balance)
  (let ((bad-pass-count 7))
    (begin
      (define (withdraw amount)
       (if (>= balance amount)
           (begin (set! balance (- balance amount))
                  balance)
           (error "Not enough money")))
      (define (deposit amount)
        (set! balance (+ balance amount))
        balance)
      (define (dispatch m)
        (cond ((eq? m 'withdraw) withdraw)
              ((eq? m 'deposit) deposit)
              (else (error "Unrecognized operation -- MAKE-ACCOUNT" m))))
      (define (call-the-cops)
        (error "Police is on the way!"))
      (lambda (pass msg)
        (if (eq? pass password)
            (begin (set! bad-pass-count 0)
                   (dispatch msg))
            (begin (set! bad-pass-count (dec bad-pass-count))
                   (if (<= bad-pass-count 0)
                       (call-the-cops))
                       (error "Password not valid")))))))

;(define acc (make-account 'secret-password 100))
;((acc 'secret-password 'withdraw) 50)
;((acc 'bad-password 'withdraw) 60)
;((acc 'secret-password 'deposit) 40)
;((acc 'secret-password 'withdraw) 40)
