#lang sicp

(define (make-account password balance)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        (error "Not enough money")))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch m)
    (cond ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unrecognized operation -- MAKE-ACCOUNT" m))))
  (lambda (pass msg)
    (if (eq? pass password)
        (dispatch msg)
        (error "Password not valid"))))

;(define acc (make-account 'secret-password 100))
;((acc 'secret-password 'withdraw) 50)
;((acc 'bad-password 'withdraw) 60)
;((acc 'secret-password 'deposit) 40)
;((acc 'secret-password 'withdraw) 40)
